### ISSUE TITLE
400 bad request при загрузке картинки на сервер

### ISSUE THREAD

**Issue by wollkey** [MrAnger/yii2-ckeditor#1]
Ошибка при загрузке картинки на сервер. Не пойму, в чём проблема, раньше работало нормально.

![2](https://user-images.githubusercontent.com/29654415/46203649-1f3a8280-c323-11e8-8891-96da1bf697a3.PNG)

Вызов метода: 

![1](https://user-images.githubusercontent.com/29654415/46203638-1944a180-c323-11e8-86d2-e7ce6fe956c8.PNG)

В шаблоне

![3](https://user-images.githubusercontent.com/29654415/46203666-2b264480-c323-11e8-8d25-56b25742ae2c.PNG)

Папки все есть, csrf отключал, не помогло. В чём может быть причина?

**Comment by MrAnger** [comment]
400 ошибка - он не нашел нужный контролер/экшен скорее всего.

Проверь, какой URL задан для загрузки в использованном пресете.

А так же, нужно ограничить версию CKEditor, они там что то наобновляли в своё время - лень разбираться.
В composer.json "ckeditor/ckeditor": "dev-full/4.7.x"

**Comment by MrAnger** [comment]
У меня такие настройки:
![image](https://user-images.githubusercontent.com/2780423/46204215-9fbeaa80-c346-11e8-9397-1e36562da4ad.png)

![image](https://user-images.githubusercontent.com/2780423/46204227-aa793f80-c346-11e8-94c4-e879cef0a909.png)

**Comment by wollkey** [comment]
Спасибо за своевременный ответ, откатил до "dev-full/4.7.x" и всё заработало.
